server:
  port: 8090
  servlet:
    context-path: /WxAuth

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html